inherit_from: .rubocop_todo.yml

Layout/AccessModifierIndentation:
  Exclude:
    - 'bin/**/*'

Layout/AlignArguments:
  Exclude:
    - 'bin/**/*'

Layout/EmptyLineAfterGuardClause:
  Exclude:
    - 'bin/**/*'

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/**/*'

Metrics/AbcSize:
  Exclude:
    - 'bin/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/CyclomaticComplexity:
  Exclude:
    - 'bin/**/*'

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'bin/bundle'
    - 'config/initializers/devise.rb'

Metrics/MethodLength:
  Exclude:
    - 'bin/**/*'

Metrics/PerceivedComplexity:
  Exclude:
    - 'bin/**/*'

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/**/*'

Style/Documentation:
  Exclude:
    - 'db/migrate/**/*'
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/controllers/application_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/ExpandPathArguments:
  Exclude:
    - 'bin/**/*'
    - 'spec/rails_helper.rb'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'db/schema.rb'
Style/IfUnlessModifier:
  Exclude:
    - 'bin/bundle'

Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'

Style/PerlBackrefs:
  Exclude:
    - 'bin/bundle'

Style/RedundantBegin:
  Exclude:
    - 'bin/yarn'

Style/SpecialGlobalVars:
  Exclude:
    - 'bin/bundle'

Style/StderrPuts:
  Exclude:
    - 'bin/yarn'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/WordArray:
  Exclude:
    - 'db/schema.rb'
